[versions]
agp = "9.0.1"
coil = "2.6.0"
hilt = "2.59.1"
arrow = "1.2.4"
kotlin = "2.3.10"
ksp = "2.3.6"
junit = "4.13.2"
moshi = "1.15.1"
timber = "5.0.1"
ok-http = "4.12.0"
coreKtx = "1.13.1"
retrofit = "2.11.0"
gsonConvertorVersion = "2.9.0"
gsonVersion = "2.8.8"
hilt-compose = "1.2.0"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
secrets-gradle = "2.0.1"
activityCompose = "1.9.2"
composeBom = "2026.02.00"
navigation-compose = "2.8.2"
lifecycleRuntimeKtx = "2.8.6"
immutable-collections = "0.3.7"
kotlinxSerializationJson = "1.6.3"
androidxComposeMaterial3Adaptive = "1.0.0-beta04"
androidxComposeMaterial3AdaptiveNavigationSuite = "1.3.0-beta05"

[libraries]
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }

androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3AdaptiveNavigationSuite" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutable-collections" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidxComposeMaterial3Adaptive" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-retrofit = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "arrow" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "ok-http" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
moshi-compiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gsonConvertorVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "ok-http" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
arrow = ["arrow-core", "arrow-retrofit"]
okhttp = ["okhttp", "okhttp-interceptor"]
retrofit = ["retrofit", "retrofit-converter"]